[project]

name = "llm4a-agd-examples"
version = "0.1.0"
description = "Examples for the LangGraph + smolagents talk"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langgraph>=0.6.6",
]
